import type { SystemGachaTemplate } from './gacha';

export const NORMAL_GACHA_TEMPLATES: SystemGachaTemplate[] = [
  {
    id: 'three-specific-praises',
    eggType: 'event',
    title: '具体地喜欢你',
    description: '今天不说泛泛的“你好可爱”，只说那些只有你才知道的细节。',
    starterTask: '认真夸对方三个非常具体的小细节，不能只夸长相。',
    partnerTask: '选出最戳心的一句，并告诉对方为什么。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'heart-outline',
  },
  {
    id: 'remote-small-help',
    eggType: 'event',
    title: '远程替你分担一点',
    description: '异地也能接住对方的一件小麻烦。',
    starterTask: '问对方：现在有什么十分钟内、我能在线帮你做的小事？',
    partnerTask: '给出一个真实的小请求，例如查资料、选照片或陪你理清一件事。',
    duration: '10 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'hand-left-outline',
  },
  {
    id: 'today-headline',
    eggType: 'event',
    title: '今天的头条新闻',
    description: '如果今天只能被记住一件事，你希望是哪一件？',
    starterTask: '把今天最想让对方知道的一件事，起成一个新闻标题。',
    partnerTask: '先猜新闻内容，再认真听完完整版。',
    duration: '8 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'chatbubbles-outline',
  },
  {
    id: 'photo-theme',
    eggType: 'event',
    title: '同题照片',
    description: '同一个主题，两双眼睛，看看不同城市里的答案。',
    starterTask: '定一个主题，比如“今天的温柔”，然后拍一张照片。',
    partnerTask: '不知道对方答案的情况下也拍一张，同时揭晓。',
    duration: '10 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'camera-outline',
  },
  {
    id: 'answer-at-once',
    eggType: 'event',
    title: '三、二、一，同时回答',
    description: '不许讨论：下次见面最想一起做什么？',
    starterTask: '语音或视频倒数三秒，同时说出心里的第一个答案。',
    partnerTask: '答案相同就加入约定，不同就各自说服对方一次。',
    duration: '5 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'flash-outline',
  },
  {
    id: 'voice-imitation',
    eggType: 'event',
    title: '模仿对方发条语音',
    description: '带着善意模仿一句最熟悉的口头禅。',
    starterTask: '用对方最常见的语气模仿一句话，录成语音发过去。',
    partnerTask: '猜出模仿的是哪个瞬间，再模仿回来；不许攻击缺点。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'shuffle-outline',
  },
  {
    id: 'old-photo',
    eggType: 'event',
    title: '随机翻到很久以前',
    description: '从旧照片里捞回一个差点被时间藏起来的瞬间。',
    starterTask: '闭眼滑动相册五秒，停下后选一张和对方有关的旧照片。',
    partnerTask: '说出当时自己记得最清楚的一个细节。',
    duration: '10 分钟',
    scene: '异地可玩',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'images-outline',
  },
  {
    id: 'emoji-story',
    eggType: 'event',
    title: '五个表情讲完今天',
    description: '文字暂时下班，只准让表情包和 emoji 出场。',
    starterTask: '用五个 emoji 概括今天，发给对方，不能解释。',
    partnerTask: '逐个猜发生了什么；猜完也交出自己的五个 emoji。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'happy-outline',
  },
  {
    id: 'bad-commercial',
    eggType: 'event',
    title: '给对象拍一条烂广告',
    description: '把对方当成最离谱、但自己最想买单的产品。',
    starterTask: '录一段十秒即兴广告发给对方，必须带一句夸张口号。',
    partnerTask: '扮演挑剔顾客，最后说出愿意“购买”的真正理由。',
    duration: '8 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'megaphone-outline',
  },
  {
    id: 'window-weather',
    eggType: 'event',
    title: '交换此刻的天空',
    description: '让对方透过一张照片，看见你所在城市的这一分钟。',
    starterTask: '现在就拍一张窗外或头顶的天空，不修图发给对方。',
    partnerTask: '也发回自己的天空，再各用一个词形容对方城市的天气。',
    duration: '4 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'cloud-outline',
  },
  {
    id: 'three-daily-fragments',
    eggType: 'event',
    title: '交换三张今日碎片',
    description: '不用等到发生大事，普通生活也值得让对方看见。',
    starterTask: '拍下今天的三样东西：吃的、看到的、正在做的，不加说明发过去。',
    partnerTask: '先猜三张照片背后的情境，再交出自己的三张今日碎片。',
    duration: '10 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'grid-outline',
  },
  {
    id: 'one-line-story',
    eggType: 'event',
    title: '一人一句写小故事',
    description: '从一句莫名其妙的开头开始，看看故事会被你们带去哪里。',
    starterTask: '写一句不超过二十字的故事开头，只能写一句。',
    partnerTask: '接着写下一句，来回五轮后一起给故事取名。',
    duration: '12 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'book-outline',
  },
  {
    id: 'childhood-snippet',
    eggType: 'event',
    title: '讲一段童年小事',
    description: '挑一件对方以前没听过、却很像现在的你的童年故事。',
    starterTask: '用语音讲一件十岁以前发生的小事，控制在一分钟内。',
    partnerTask: '听完后说说：这件事和现在的你，哪里最像？',
    duration: '8 分钟',
    scene: '异地可玩',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'balloon-outline',
  },
  {
    id: 'same-drink-toast',
    eggType: 'event',
    title: '隔空碰个杯',
    description: '不必喝同一种东西，也可以在同一秒为彼此举杯。',
    starterTask: '拿起手边的水或饮料，拍照发出“准备好了”。',
    partnerTask: '也准备一杯，视频或语音倒数三秒，隔空碰杯。',
    duration: '5 分钟',
    scene: '异地专属',
    color: '#6FAFA1',
    softColor: '#E6F5F1',
    icon: 'cafe-outline',
  },
  {
    id: 'mood-color',
    eggType: 'event',
    title: '今天是什么颜色',
    description: '先不说开心或难过，用一种颜色讲今天。',
    starterTask: '选一种代表今天心情的颜色，拍到或截图发给对方。',
    partnerTask: '先猜原因，再交出自己的颜色和答案。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'color-palette-outline',
  },
  {
    id: 'meme-remake',
    eggType: 'event',
    title: '复刻一张表情包',
    description: '选一张常用表情包，用自己的脸或手边物品复刻它。',
    starterTask: '挑一张表情包进行低成本复刻，拍照发给对方。',
    partnerTask: '猜原图并打分，然后也接受一张复刻挑战。',
    duration: '10 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'happy-outline',
  },
  {
    id: 'new-discovery',
    eggType: 'event',
    title: '交换一个新发现',
    description: '把今天刚知道的小知识、小店或小爱好分享给对方。',
    starterTask: '分享一个今天新发现的东西，并说为什么想到对方。',
    partnerTask: '认真看完后给出一个问题，再分享自己的新发现。',
    duration: '8 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'telescope-outline',
  },
  {
    id: 'guess-current-pose',
    eggType: 'event',
    title: '猜猜我现在什么姿势',
    description: '只给三个线索，让对方猜猜你此刻的生活现场。',
    starterTask: '用三个词描述自己现在的姿势和环境，不能直接说答案。',
    partnerTask: '画个简笔画或用文字猜现场，然后交换角色。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'body-outline',
  },
  {
    id: 'desk-corner',
    eggType: 'event',
    title: '晒晒书桌一角',
    description: '不用整理，就让对方看见你此刻真实的小角落。',
    starterTask: '拍一张书桌、床边或沙发角，不用解释直接发过去。',
    partnerTask: '也从自己的空间里选一处回拍，并猜对方现在可能在做什么。',
    duration: '3 分钟',
    scene: '异地专属',
    color: '#7FA9C6',
    softColor: '#E7F1FA',
    icon: 'desktop-outline',
  },
  {
    id: 'song-recommend',
    eggType: 'event',
    title: '随手推一首歌',
    description: '不用解释太多，把此刻耳机里的旋律分享出去。',
    starterTask: '分享一首现在想听或正在听的歌，附一句“因为像你/像今天”。',
    partnerTask: '听完或收藏后，也回推一首并说说联想到了什么。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#6FAFA1',
    softColor: '#E6F5F1',
    icon: 'musical-note-outline',
  },
  {
    id: 'weather-swap',
    eggType: 'event',
    title: '交换两城天气',
    description: '各自报出此刻的温度、天气和一个身体感受。',
    starterTask: '发一张天气截图或语音报温度，再说今天体感是冷是热还是闷。',
    partnerTask: '也报出自己的城市天气，并猜对方那边现在穿什么。',
    duration: '4 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'partly-sunny-outline',
  },
  {
    id: 'guess-activity',
    eggType: 'event',
    title: '猜对方在干嘛',
    description: '只靠直觉，猜猜对方这一分钟的生活现场。',
    starterTask: '用一句话猜对方现在正在做什么，可以离谱但要有画面感。',
    partnerTask: '公布真实答案，并也猜一次你正在做什么。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'help-circle-outline',
  },
  {
    id: 'favorite-meme',
    eggType: 'event',
    title: '解释一张爱用表情包',
    description: '让对方知道，你发这个表情时心里在想什么。',
    starterTask: '发一张最近最常用的表情包，用一句话解释它的使用场景。',
    partnerTask: '也发一张自己的，并模仿对方语气用一次。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'chatbox-ellipses-outline',
  },
  {
    id: 'three-words-today',
    eggType: 'event',
    title: '三个词形容今天',
    description: '比长篇大论更快，把今天的质地交给三个词。',
    starterTask: '用三个词形容今天，不许重复，发文字或语音都行。',
    partnerTask: '先猜这三个词背后的原因，再交出自己的三个词。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'text-outline',
  },
  {
    id: 'share-link',
    eggType: 'event',
    title: '分享正在看的东西',
    description: '把屏幕里这一小段生活递给对方。',
    starterTask: '分享一个正在看的视频、文章或帖子，附一句“想到你了”。',
    partnerTask: '看完后回一个表情或问题，也分享一个自己的。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#7FA9C6',
    softColor: '#E7F1FA',
    icon: 'link-outline',
  },
  {
    id: 'next-meal-dream',
    eggType: 'event',
    title: '下次见面第一顿饭',
    description: '先在心里吃一遍那顿期待已久的饭。',
    starterTask: '描述下次见面最想一起吃的一顿饭，具体到菜和氛围。',
    partnerTask: '在这顿饭里再加一道自己想点的菜。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'restaurant-outline',
  },
  {
    id: 'cold-joke',
    eggType: 'event',
    title: '交换一个冷笑话',
    description: '好笑不好笑不重要，重要的是让对方笑一下。',
    starterTask: '讲一个冷笑话或谐音梗，语音文字都行。',
    partnerTask: '诚实评价冷度，并回敬一个更冷的。',
    duration: '3 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'snow-outline',
  },
  {
    id: 'night-view',
    eggType: 'event',
    title: '交换窗外夜景',
    description: '各自城市的夜晚，也值得被看见。',
    starterTask: '拍一张窗外夜景或路灯，不用修图。',
    partnerTask: '也发一张自己的，并猜对方那边现在几点、累不累。',
    duration: '5 分钟',
    scene: '异地专属',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'moon-outline',
  },
  {
    id: 'doodle-for-you',
    eggType: 'event',
    title: '画个小涂鸦',
    description: '画得好不好不重要，重要的是专门画给对方。',
    starterTask: '在纸上或备忘录里画个小涂鸦，拍照发给对方。',
    partnerTask: '猜猜画的是什么，再回赠一幅简笔画。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'brush-outline',
  },
  {
    id: 'drink-of-day',
    eggType: 'event',
    title: '推荐今日饮品',
    description: '把手里这杯喝的，变成一句想念。',
    starterTask: '拍一杯今天的饮料，说为什么此刻想喝这个。',
    partnerTask: '也拍一杯自己的，并猜对方喝起来是什么心情。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#6FAFA1',
    softColor: '#E6F5F1',
    icon: 'beer-outline',
  },
  {
    id: 'guess-meal',
    eggType: 'event',
    title: '猜对方今天吃了啥',
    description: '用了解程度，赌一顿虚拟外卖。',
    starterTask: '猜对方今天午饭或晚饭吃了什么，可以猜三道菜。',
    partnerTask: '公布答案并附一张食物照片，也猜一次你的。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'fast-food-outline',
  },
  {
    id: 'wallpaper-share',
    eggType: 'event',
    title: '分享手机壁纸',
    description: '一张壁纸，有时比自拍更能说明心情。',
    starterTask: '截图当前壁纸发给对方，说为什么一直没换。',
    partnerTask: '也分享自己的壁纸，并猜对方最近的状态。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'phone-portrait-outline',
  },
  {
    id: 'haiku-mini',
    eggType: 'event',
    title: '写一句迷你诗',
    description: '不用押韵，三行以内，把今天折成一句诗。',
    starterTask: '写三行以内的小诗，主题不限，但必须提到对方或距离。',
    partnerTask: '读完后也写一句回诗，可以接龙也可以另起。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#9A87D8',
    softColor: '#F0ECFC',
    icon: 'create-outline',
  },
  {
    id: 'movie-pick',
    eggType: 'event',
    title: '推荐一部想一起看的片',
    description: '先隔空看，等见面再一起重温。',
    starterTask: '推荐一部电影或剧集，说最想和对方一起看哪一段。',
    partnerTask: '也推荐一部，并约定谁先去看。',
    duration: '6 分钟',
    scene: '异地可玩',
    color: '#7FA9C6',
    softColor: '#E7F1FA',
    icon: 'film-outline',
  },
  {
    id: 'if-you-were-here',
    eggType: 'event',
    title: '如果你在身边',
    description: '把“要是你在就好了”说得更具体一点。',
    starterTask: '补完这句话：如果你现在在我身边，我会拉着你去……',
    partnerTask: '也补完自己的版本，看看有没有重合的小愿望。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'heart-half-outline',
  },
  {
    id: 'first-bite-photo',
    eggType: 'event',
    title: '今日第一口食物',
    description: '从第一口开始，把今天的生活分给对方一半。',
    starterTask: '拍今天吃的第一口或最喜欢的一口，不用摆盘。',
    partnerTask: '也发一张自己的，并猜对方这顿吃得开不开心。',
    duration: '4 分钟',
    scene: '异地专属',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'nutrition-outline',
  },
  {
    id: 'emoji-for-partner',
    eggType: 'event',
    title: '一个 emoji 形容对方',
    description: '今天在你眼里，对方像哪个表情？',
    starterTask: '只发一个 emoji 形容对方今天的样子，暂时不许解释。',
    partnerTask: '猜为什么选这个，再回赠一个形容对方的 emoji。',
    duration: '3 分钟',
    scene: '异地可玩',
    color: '#E38462',
    softColor: '#FCEAE2',
    icon: 'happy-outline',
  },
  {
    id: 'voice-hum',
    eggType: 'event',
    title: '哼一段让对方猜歌',
    description: '不用唱全曲，几句哼唱就够。',
    starterTask: '哼一段旋律（可以跑调），让对方猜歌名或心情。',
    partnerTask: '公布答案后，也哼一段自己的给对方猜。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#6FAFA1',
    softColor: '#E6F5F1',
    icon: 'mic-outline',
  },
  {
    id: 'handwriting-note',
    eggType: 'event',
    title: '手写几个字',
    description: '纸上的字，有时比打字更暖。',
    starterTask: '在纸上手写一句想对对方说的话，拍照发过去。',
    partnerTask: '也手写一句回给对方，可以接上一句或另起一行。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#E8899C',
    softColor: '#FDE9EE',
    icon: 'pencil-outline',
  },
  {
    id: 'comfort-item',
    eggType: 'event',
    title: '拍一件安慰你的小东西',
    description: '毛绒玩具、杯子、毯子……什么都可以。',
    starterTask: '拍一件此刻让你安心的小物件，说它在替你陪谁。',
    partnerTask: '也拍一件自己的，并猜对方今天需不需要被安慰。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#7FA9C6',
    softColor: '#E7F1FA',
    icon: 'cube-outline',
  },
  {
    id: 'voice-check-in',
    eggType: 'event',
    title: '十五秒状态播报',
    description: '像电台一样，简短播报自己现在的状态。',
    starterTask: '录一段不超过十五秒的语音：在哪、在干嘛、心情如何。',
    partnerTask: '听完也录一段自己的，最后互相回一个“收到”。',
    duration: '3 分钟',
    scene: '异地专属',
    color: '#6FAFA1',
    softColor: '#E6F5F1',
    icon: 'radio-outline',
  },
  {
    id: 'future-wish',
    eggType: 'event',
    title: '说一句见面倒数愿望',
    description: '把等待变成一件具体的小事。',
    starterTask: '说一件下次见面最想一起做的小事，越具体越好。',
    partnerTask: '在这件小事里加一个自己想加的细节。',
    duration: '5 分钟',
    scene: '异地可玩',
    color: '#D4A64E',
    softColor: '#FBF2DC',
    icon: 'hourglass-outline',
  },
  {
    id: 'screen-time-share',
    eggType: 'event',
    title: '分享屏幕使用时间',
    description: '一点点自嘲，一点点真实。',
    starterTask: '截图或口述今天屏幕使用时间最长的一个 App，说说原因。',
    partnerTask: '也分享自己的，并猜对方今天有没有偷偷想自己。',
    duration: '4 分钟',
    scene: '异地可玩',
    color: '#6E9FCB',
    softColor: '#E7F1FA',
    icon: 'stats-chart-outline',
  },
];
